### ISSUE TITLE
when loading bpha-limited starts with Hyde version and then changes

### ISSUE THREAD

**Issue by Katie-Hyde** [yalla-coop/universal-credit-support#479] opened 2023-12-08 08:39 UTC
### Please select the priority level by adding one of the following labels to this issue?

Priority-4 (Low e.g. Content is not perfectly aligned)

### Describe the bug and the expected behaviour.

background splits between Hyve version and then loads BPHA version

### Steps To Reproduce

load bpha-limited
![20231207_085715](https://github.com/yalla-coop/universal-credit-support/assets/87085422/b4b5ad4b-42df-4b79-89d0-6120d2f9f185)

### Screenshots or a link to a Loom Recording

![20231207_085715](https://github.com/yalla-coop/universal-credit-support/assets/87085422/4ee75720-47e1-44b2-83de-1b02c357e21f)

**Comment by cyberteenie** [comment] 2023-12-18 11:35
Hi @Katie-Hyde - sorry about that! We will hide that glitch.

**Comment by RamyAlshurafa** [comment] 2024-01-31 21:09
Hey @Katie-Hyde 
this is fixed now, can you check please?

**Comment by HYDETS38** [comment] 2024-02-02 09:15
Hi,
Yes, I've verified this and confirmed with the partner org. It seems to be resolved now.
many thanks.

**Comment by HYDETS38** [comment] 2024-02-02 09:16
The ticket can be closed.

**Closed as completed** 2024-02-05 09:27 UTC
Labels: bug, sla
